#!/usr/bin/env python3
"""
send_email_report.py

Sends the latest Debt Review report (Excel) via SMTP.
Designed to run inside GitHub Actions after refresh_metrics.py.

Environment variables (set via GitHub Secrets):
    SMTP_SERVER    e.g. smtp.gmail.com
    SMTP_PORT      e.g. 587 (STARTTLS) or 465 (SSL)
    SMTP_USER      SMTP login username (usually the sender's email)
    SMTP_PASSWORD  SMTP password or app password
    EMAIL_FROM     From address (defaults to SMTP_USER)
    EMAIL_TO       Recipient(s), comma-separated for multiple
"""

import os
import sys
import glob
import smtplib
import ssl
from email.message import EmailMessage
from datetime import datetime


# ------------------------------------------------------------------
# 1. Read + validate environment
# ------------------------------------------------------------------
def env(name: str, default: str = "") -> str:
    """Return env var or default, treating empty strings as unset."""
    val = os.getenv(name)
    return val if val not in (None, "") else default


SMTP_SERVER   = env("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT_RAW = env("SMTP_PORT", "587")
SMTP_USER     = env("SMTP_USER")
SMTP_PASSWORD = env("SMTP_PASSWORD")
EMAIL_FROM    = env("EMAIL_FROM", SMTP_USER)
EMAIL_TO      = env("EMAIL_TO")

print("=" * 60)
print("SMTP configuration")
print("=" * 60)
print(f"  SMTP_SERVER   : {SMTP_SERVER!r}")
print(f"  SMTP_PORT     : {SMTP_PORT_RAW!r}")
print(f"  SMTP_USER     : {SMTP_USER!r}")
print(f"  SMTP_PASSWORD : {'*' * len(SMTP_PASSWORD) if SMTP_PASSWORD else '(empty)'}")
print(f"  EMAIL_FROM    : {EMAIL_FROM!r}")
print(f"  EMAIL_TO      : {EMAIL_TO!r}")
print("=" * 60)

# Fail fast with a clear message rather than a cryptic traceback
missing = [name for name, val in [
    ("SMTP_SERVER",   SMTP_SERVER),
    ("SMTP_PORT",     SMTP_PORT_RAW),
    ("SMTP_USER",     SMTP_USER),
    ("SMTP_PASSWORD", SMTP_PASSWORD),
    ("EMAIL_FROM",    EMAIL_FROM),
    ("EMAIL_TO",      EMAIL_TO),
] if not val]

if missing:
    print(f"❌ Missing required configuration: {', '.join(missing)}")
    print("   Check that these GitHub Secrets are set in the repo "
          "(Settings → Secrets and variables → Actions).")
    sys.exit(1)

try:
    SMTP_PORT = int(SMTP_PORT_RAW)
except ValueError:
    print(f"❌ SMTP_PORT must be an integer, got {SMTP_PORT_RAW!r}")
    sys.exit(1)

# Split recipients (supports "a@x.com, b@y.com")
recipients = [addr.strip() for addr in EMAIL_TO.split(",") if addr.strip()]
if not recipients:
    print("❌ EMAIL_TO did not contain any valid addresses.")
    sys.exit(1)


# ------------------------------------------------------------------
# 2. Find the report file(s) to attach
# ------------------------------------------------------------------
def find_reports() -> list:
    """Look for the most recent Excel report generated by refresh_metrics.py."""
    patterns = [
        "Debt_Review_Dashboard_*.xlsx",
        "*.xlsx",
        "reports/*.xlsx",
        "history/*.xlsx",
    ]
    found = []
    for pat in patterns:
        found.extend(glob.glob(pat))
        if found:
            break

    if not found:
        return []

    # Newest first
    found.sort(key=os.path.getmtime, reverse=True)
    # Return only the newest to avoid attaching every historical report
    return [found[0]]


attachments = find_reports()
print(f"📎 Attachments found: {attachments if attachments else '(none)'}")


# ------------------------------------------------------------------
# 3. Build the email
# ------------------------------------------------------------------
today_str = datetime.now().strftime("%d %B %Y")

msg = EmailMessage()
msg["Subject"] = f"Debt Review Report — {today_str}"
msg["From"]    = EMAIL_FROM
msg["To"]      = ", ".join(recipients)

body = f"""Hi,

Please find attached the Debt Review report for {today_str}.

This email was generated automatically by the Debt Review Dashboard workflow.

Regards,
Debt Review Dashboard
"""
msg.set_content(body)

for path in attachments:
    try:
        with open(path, "rb") as f:
            data = f.read()
        filename = os.path.basename(path)
        msg.add_attachment(
            data,
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            filename=filename,
        )
        print(f"   attached: {filename} ({len(data):,} bytes)")
    except Exception as e:
        print(f"⚠️  Could not attach {path}: {e}")


# ------------------------------------------------------------------
# 4. Send
# ------------------------------------------------------------------
def send_via_ssl():
    """Port 465 style — implicit TLS."""
    ctx = ssl.create_default_context()
    with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, context=ctx, timeout=30) as server:
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.send_message(msg)


def send_via_starttls():
    """Port 587 style — plaintext connect, upgrade with STARTTLS."""
    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=30) as server:
        server.ehlo()
        server.starttls(context=ssl.create_default_context())
        server.ehlo()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.send_message(msg)


try:
    print(f"📧 Connecting to {SMTP_SERVER}:{SMTP_PORT} …")
    if SMTP_PORT == 465:
        send_via_ssl()
    else:
        send_via_starttls()

    print(f"✅ Email sent successfully to: {', '.join(recipients)}")
    if attachments:
        print(f"   with attachment: {os.path.basename(attachments[0])}")

except smtplib.SMTPAuthenticationError as e:
    print("❌ SMTP authentication failed.")
    print("   For Gmail: you MUST use a 16-character App Password, not your login password.")
    print("   Enable 2FA at https://myaccount.google.com/security")
    print("   Then generate an app password at https://myaccount.google.com/apppasswords")
    print(f"   Server said: {e}")
    sys.exit(1)

except smtplib.SMTPException as e:
    print(f"❌ SMTP error: {e}")
    sys.exit(1)

except Exception as e:
    print(f"❌ Unexpected error sending email: {e!r}")
    sys.exit(1)
